spring:
  cloud:
    consul:
      discovery:
        health-check-interval: 3s
        health-check-path: /actuator/health
        heartbeat:
          enabled: true
        health-check-url: ${spring.cloud.client.ip-address}:${server.port}
  datasource:
    url: jdbc:mysql://10.88.247.103:3306/db_project_001?serverTimezone=UTC&characterEncoding=utf8&useUnicode=true&useSSL=false
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis:
  type-aliases-package: com.dwline.duwa.cloud.provider.entity
  mapper-locations: classpath*:mapper/*Mapper.xml
